apiVersion: v1
kind: Service
metadata:
  name: discord-article-bot-agent
  namespace: discord-article-bot
spec:
  selector:
    app: discord-article-bot-agent
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
